### ISSUE TITLE
Week 06 Day 3 - Pet Adoption  - 

### ISSUE THREAD

**Issue by mdewey** [Kemenyfy/Assignments#23]
For this project, you will forking an existing repo and adding ore functionality to it. You will completing the UI as well as adding a "save for later" feature. 

## Objectives

* Work with creating components
* Work with a Github workflow
* Work with local storage

## Requirements

First you need ot fork this repo [https://github.com/mdewey/puppy-adoption](https://github.com/mdewey/puppy-adoption). 

Then you will need to clone your fork to your local machine. You will be doing all of your development on that fork. 

### Explorer Mode

* [x] Add some styling to the page. Make the header look like a header, add styling to the nav bar, and style the pets using flexbox to wrap around the page. 
* [x] Make a `Pet` component to have all logic, HTML and styling for a pet. 
* [x] Hook up the `Save for later! Arf!` to save the current pet to local storage. 
* [ ] On the main page, display the number of pets save to local storage
* [ ] Submit a pull request back to [https://github.com/mdewey/puppy-adoption](https://github.com/mdewey/puppy-adoption)

### Adventure Mode

* [ ] Add React Router and create the follow pages: 
    - [ ] Index page to view all pets
    - [ ] a page to view my saved pets
    - [ ] a page to view all the details about a pet
* [ ] Add more information to each Pet on the index page. 

*NOTE*: Remember to think in components

### Epic Mode

* [ ] Add search filters and a easier UI to discover pets for their family

**Comment by Kemenyfy** [comment]
https://github.com/Kemenyfy/Pet-Adoption

**Comment by mdewey** [comment]
![Awesome Work!](https://media2.giphy.com/media/xULOFmW3qoXS0/200w_d.gif)
