### ISSUE TITLE
Final Project 4 - #Ship it - 

### ISSUE THREAD

**Issue by mdewey** [Kemenyfy/Assignments#43]
With all the work you have been putting into the last 12 weeks, it has all come down to this. Complete your capstone and show it to the world

## Explorer Mode

- [x] Submit your repository for the capstone project
- [x] Submit your Url(s) for your capstone project.

**Comment by Kemenyfy** [comment]
https://github.com/Kemenyfy/DevsCultureVue

devsculture.com

**Comment by mdewey** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media1.giphy.com/media/xWpSOshpxSvfYQmKxz/200w_d.gif)
