### ISSUE TITLE
Week 02 Day 1 - Scoreboard - 

### ISSUE THREAD

**Issue by mdewey** [Kemenyfy/Assignments#5]
# Score Board

For this assignment you will creating a simple interactive score board for your favorite sport.

A User should be able to update a score and the teams playing.

### Explorer Mode

Should resemble this:
![markup](https://raw.githubusercontent.com/suncoast-devs/handbook/master/content/curriculum/fundamentals/javascript/assignments/assets/scoreboard-day-1.buttons.PNG)

- [x] implement the basic HTML
- [x] implement the basic formating. Do not worry about styling (colors and fonts and the like)
- [x] add click events to the `update` buttons to update the corresponding values on the page. The score buttons should adjust the current score by a "hard coded" value

### Adventure Mode

- [x] Complete Explorer Mode
- [x] Implement a Quarter/Period Tracker that would be appropriate for the sport
- [x] Add some custom CSS to make it more colorful. Have fun with it
- [x] Make the layout responsive

### Epic Mode

- [x] Add a Timer that counts down automatically and updates the period/quarter appropriately
- [x] Save/load the information to local storage
- [ ] Add CSS to the winning teams score to indicate who is currently winning
- [ ] add anything else that your sport would have on its score board (fouls, sacks, shots on goal, etc);
- [x] Improve the UX to help making score keeping by your sport easier

**Comment by Kemenyfy** [comment]
https://github.com/Kemenyfy/scoreboard

**Comment by mdewey** [comment]
![Awesome Work!](https://media0.giphy.com/media/3ov9jSJvoM3HyvcEQU/200w_d.gif)
